services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
    - '.:/var/www'
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
    - '${APP_PORT:-80}:80'
    volumes:
    - '.:/var/www'
    links:
      - php
    depends_on:
      - php
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    ports:
    - '${MYSQL_PORT:-3306}:3306'
    volumes:
    - 'app_volume:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_volume:
    driver: local
