services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    env_file:
      - docker/docker.env
    volumes:
    - '.:/var/www'
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
      args:
        ROOT_PATH: ${ROOT_PATH:-/var/www/public}
    env_file:
      - docker/docker.env
    ports:
    - '${APP_PORT:-80}:80'
    - '${APP_SECURE_PORT:-443}:443'
    volumes:
    - '.:/var/www'
    links:
      - php
    depends_on:
      - php
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    ports:
    - '${MYSQL_PORT:-3306}:${DB_PORT:-3306}'
    volumes:
    - 'mysql_volume:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    networks:
      - app_network

  redis:
    image: redis:6.2-alpine
    ports:
    - '6379:6379'
    volumes:
    - 'redis_volume:/var/lib/redis'
    environment:
      REDIS_REPLICATION_MODE: master

networks:
  app_network:
    driver: bridge

volumes:
  mysql_volume:
    driver: local
  redis_volume:
    driver: local
