services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
    - '.:/var/www'
    depends_on:
      - mysql
    networks:
      - app_network

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
    - '8888:80'
    volumes:
    - '.:/var/www'
    links:
      - php
    depends_on:
      - php
    networks:
      - app_network

  mysql:
    image: 'mysql:8.0'
    ports:
    - '33061:3306'
    volumes:
    - 'app_volume:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_volume:
    driver: local
